<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

|Term|Brief Description|
|:---:|:---:|
|Subsetting|Selecting a section of the list/array|
|Indexing|Selecting an element of the list/array|
|Slicing|Selecting a range of elements of the list/array|
|Masking|Selecting for elements that fulfill a specified condition|

In [2]:
import numpy as np
import numpy.ma as ma

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                       [10, "J"], [9, "I"]])

In [5]:
%%timeit
list = []
for x in np_array_2d:
    if int(x[0]) % 2 == 1:
        list.append(x[1])
#print(np.array(list).astype(str))

6.54 µs ± 88.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%%timeit
#With numpy functions
numbers_subset = np_array_2d[:,0].astype(int)
mask = numbers_subset % 2 != 0
odd_letts = np_array_2d[mask]
#odd_letts

6.62 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
arr = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]
arr = np.array(arr)
arr1 = arr[arr < 50]
print(arr1)
arr[arr < 50] = -1
arr[arr > 50] = 1
arr[arr == 50] = 0
print(arr)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
